"""add_image_columns

Revision ID: 896ccb555f59
Revises: 3758ba2738b7
Create Date: 2026-03-15 13:30:26.382119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '896ccb555f59'
down_revision: Union[str, Sequence[str], None] = '3758ba2738b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seedlings', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('seedlings', sa.Column('thumbnail_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seedlings', 'thumbnail_url')
    op.drop_column('seedlings', 'image_url')
    # ### end Alembic commands ###
