name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install Python and Dependencies
        run: |
          uv python install
          uv sync --all-extras --dev

      - name: Run Migrations
        env:
            DATABASE_URL: "sqlite:///./test.db"
        run: uv run alembic upgrade head

      - name: Run Pytest (Unit/Integration)
        env:
          DATABASE_URL: "sqlite:///./test.db"
        run: uv run pytest

      - name: Run Behave (BDD/Behavioral)
        env:
            TESTING: "true"
            DATABASE_URL: "sqlite:///./test.db"
            AWS_ACCESS_KEY_ID: testing
            AWS_SECRET_ACCESS_KEY: testing
            AWS_DEFAULT_REGION: us-east-1
        run: uv run behave --format plain --no-capture